# url: http://tylertate.com/
url: http://127.0.0.1:4000
navigation:
- text: About
  url: /about.html
- text: Work
  url: /work.html
- text: Writings
  url: /writings.html
  layout: blog
- text: Talks
  url: /talks.html